#!/usr/bin/env python3
"""Tidy the built fonts and assemble the specimen site's assets.

    python scripts/21_specimen.py

Does two jobs that belong together:

1. Sorts `dist/` - which the build fills flat - into one folder per family,
   with the full TTFs, the app-sized Latin cuts, and woff2 for the web.
2. Copies the woff2 into `specimen/fonts/` and writes `specimen/fonts.css`,
   so the specimen page can be opened straight off the filesystem with no
   server and no CDN.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from fontTools.ttLib import TTFont

from vavin import config as C

SPECIMEN = C.ROOT / "specimen"


def family_dir(family: str) -> Path:
    return C.DIST / family.replace(" ", "")


def tidy() -> dict[str, list[Path]]:
    """Sort the flat build output into one folder per family."""
    organised: dict[str, list[Path]] = {}
    for family, recipe in C.FAMILIES.items():
        target = family_dir(family)
        (target / "ttf").mkdir(parents=True, exist_ok=True)
        (target / "app").mkdir(parents=True, exist_ok=True)
        (target / "web").mkdir(parents=True, exist_ok=True)
        organised[family] = []

        for style in recipe["styles"]:
            base = C.ps_name(style, family)
            full = C.DIST / f"{base}.ttf"
            latin = C.DIST / f"{base}-Latin.ttf"
            if not full.exists():
                continue
            shutil.move(str(full), target / "ttf" / full.name)
            if latin.exists():
                shutil.move(str(latin), target / "app" / latin.name)

            font = TTFont(target / "ttf" / full.name)
            font.flavor = "woff2"
            web = target / "web" / f"{base}.woff2"
            font.save(web)
            organised[family].append(web)
    return organised


CSS_HEAD = """/* Vavin — generated by scripts/21_specimen.py, do not edit by hand. */
"""


def write_css(organised: dict[str, list[Path]]) -> Path:
    (SPECIMEN / "fonts").mkdir(parents=True, exist_ok=True)
    rules = [CSS_HEAD]
    for family, recipe in C.FAMILIES.items():
        for style in recipe["styles"]:
            spec = C.STYLES[style]
            base = C.ps_name(style, family)
            src = family_dir(family) / "web" / f"{base}.woff2"
            if not src.exists():
                continue
            shutil.copy(src, SPECIMEN / "fonts" / src.name)
            rules.append(
                "@font-face {\n"
                f'  font-family: "{family}";\n'
                f'  src: url("fonts/{src.name}") format("woff2");\n'
                f"  font-weight: {spec['weight_class']};\n"
                f"  font-style: {'italic' if spec['italic'] else 'normal'};\n"
                "  font-display: block;\n"
                "}"
            )
    # The specimen's before/after comparator needs the source face too, or the
    # one claim the whole project rests on cannot be shown.
    reference = _reference_woff2()
    if reference:
        rules.append(
            "@font-face {\n"
            '  font-family: "EB Garamond";\n'
            f'  src: url("fonts/{reference.name}") format("woff2");\n'
            "  font-weight: 400;\n"
            "  font-style: normal;\n"
            "  font-display: block;\n"
            "}"
        )

    path = SPECIMEN / "fonts.css"
    path.write_text("\n".join(rules) + "\n", encoding="utf-8")
    return path


def _reference_woff2() -> Path | None:
    """Upstream EB Garamond Regular as woff2, for the comparator."""
    from fontTools.varLib import instancer

    target = SPECIMEN / "fonts" / "EBGaramond-Regular.woff2"
    if target.exists():
        return target
    if not C.UPSTREAM_VF.exists():
        return None
    font = instancer.instantiateVariableFont(
        TTFont(C.UPSTREAM_VF), {"wght": 400}, inplace=False
    )
    font.flavor = "woff2"
    font.save(target)
    return target


def main() -> int:
    if not any(C.DIST.glob("*.ttf")) and not any(C.DIST.iterdir()):
        print("!! nothing built. run scripts/03_restyle.py --subset", file=sys.stderr)
        return 1

    SPECIMEN.mkdir(parents=True, exist_ok=True)
    organised = tidy()
    css = write_css(organised)

    print()
    for family, files in organised.items():
        target = family_dir(family)
        total = sum(f.stat().st_size for f in target.rglob("*") if f.is_file())
        print(f"  {family:<22} {len(files)} styles   {total // 1024:>5} kB"
              f"   {target.relative_to(C.ROOT)}/")
    print(f"\n  {css.relative_to(C.ROOT)}")
    print(f"  {(SPECIMEN / 'fonts').relative_to(C.ROOT)}/"
          f"  ({len(list((SPECIMEN / 'fonts').glob('*.woff2')))} woff2)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
